//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2021_12_27_webformV2.L1_MasterPage
{


    public partial class _1_07FindControl1
    {
    }
}
